### ISSUE TITLE
Best way to use inline css styles ?

### ISSUE THREAD

**Issue by EugeneLiang** [reactjs/react-php-v8js#10]
Hi good day, 

May i know how can we use CSS inline styles ( https://facebook.github.io/react/tips/inline-styles.html ) using react-php-v8js ?

Been googling around and can't really find a definitive answer.

Cheers!

**Comment by jbroadice** [comment]
If you're using something like Browserify to bundle up your Javascript, you could use [ReactCSS](https://github.com/casesandberg/reactcss) to solve this problem. It allows you to couple the style definitions with the component directly.

**Comment by zpao** [comment]
I don't think there's anything special about react-php-v8js here so I'm going to close out.
