### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by qpautrat** [reactjs/react-php-v8js#12]
Hi @zpao ,

Is it possible to tag a release ?

**Comment by zpao** [comment]
We haven't had any "releases" and there isn't a version number in the repo. Happy to do it and make up a version number but can't do it without knowing the goal (presumably it's for composer, which might only read the version from tags?)

**Comment by qpautrat** [comment]
You are absolutly right. 
Actually people have to whitelist this library in their root composer.json due to dev minimum stability.

**Comment by zpao** [comment]
Cool, tagged v1.0.0. https://github.com/reactjs/react-php-v8js/tree/v1.0.0

**Comment by qpautrat** [comment]
Thanks !
