### ISSUE TITLE
Register in packagist

### ISSUE THREAD

**Issue by qpautrat** [reactjs/react-php-v8js#13]
Hi @zpao ,

I am really sorry to bother you with that.
I have a final request to ask you. Is this possible to publish it on packagist ?

**Comment by zpao** [comment]
It's already published - https://packagist.org/packages/reactjs/react-php-v8js. cc @talyssonoc who did that (also, can you add me as an owner)

**Comment by talyssonoc** [comment]
Sure, @zpao, what's your Packagist username ?

**Comment by zpao** [comment]
zpao

**Comment by talyssonoc** [comment]
Just did it !

**Comment by zpao** [comment]
Thanks @talyssonoc!

@qpautrat Looks like it's updated now for 1.0.0 and I setup the webhook so it'll get autoupdated in the future.

**Comment by qpautrat** [comment]
@zpao Great, thanks !
