### ISSUE TITLE
Issue new release

### ISSUE THREAD

**Issue by sisve** [reactjs/react-php-v8js#21]
The current stable (1.0.0) is behind the master branch with some important commits that fixes deprecation warnings like "Warning: React.renderToString is deprecated. Please use ReactDOMServer.renderToString from require('react-dom/server') instead.". A workaround is using dev-master and minimum-stability:dev which makes my skin itch...

The relevant commit: https://github.com/reactjs/react-php-v8js/commit/05637dbb62fa139b7edacfaf782341d9c9e8c34f

**Comment by zpao** [comment]
What's the typical way people declare their composer dependencies? If I tag master as 1.1.0, is that likely to break a bunch of people? Should I just call it 2.0.0 to be safe?

**Comment by sisve** [comment]
I don't think that you need to consider how people have referenced your library, if they wanted an explicit version they would have explicitly referred to that. Just make sure you're consistent in your versioning and following the semver rules.
- Are all changes internal backward compatible bug-fixes? Then it's a 1.0.1.
- Is there new functionality but the public api is backward compatible? Then it's a 1.1.0.
- Are there backwards incompatible changes in the public api? Then it should be 2.0.0.

**Comment by zpao** [comment]
tagged master as 2.0.0
