### ISSUE TITLE
setTimeout is not defined

### ISSUE THREAD

**Issue by rajivseelam** [reactjs/react-php-v8js#29]
Hi,

I keep getting this error:

V8Js::compileString():78458: ReferenceError: setTimeout is not defined

I am not sure where to start to solve this issue.

**Comment by jurgenzz** [comment]
I had the same issue, resolved it by adding this on top of my build:

``` js

if (!global.setTimeout) {
    global.setTimeout = null;
}
```

**Comment by jordmccord** [comment]
I'm having the same issue tried adding the "global.setTimeout = null;" and it is now saying "null is not a function!"

**Comment by jurgenzz** [comment]
Try making it as a function?

``` js
if (!global.setTimeout) {
    global.setTimeout = function() {};
}
```

**Comment by rajivseelam** [comment]
@jurgenzz 

Where should we add this? Please let us know. Any file for example, very new to JS.

**Comment by jurgenzz** [comment]
Either on to of your entry file, if you are doing a build or just on top of the component file you are targeting with react-php

**Comment by zpao** [comment]
Your JS is being loaded directly into V8, so you don't have things that aren't part of ECMAScript (Eg anything that is defined on `window` in the browser context or other globals that node might set up)
