### ISSUE TITLE
Best way to enable using JSX with this?

### ISSUE THREAD

**Issue by brenelz** [reactjs/react-php-v8js#4]

**Comment by zpao** [comment]
You can preprocess (with react-tools or babel from node) or do something like what pyreact or react-rails do (load JSXTransfomer into context and run the code through that transform fn)

**Comment by brenelz** [comment]
Yeah... I kind of have it figured out.  Browserify also works...

**Comment by Webkadabra** [comment]
@brenelz could you please share your solution?
